
tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: stable
  goland:
    prebuilds:
      version: latest
  pycharm:
    prebuilds:
      version: both
